Rebase the repo
AdfPizarro/awesome_books pull request #7
Opened 2021-08-11 19:48 UTC by AdfPizarro

Add css styling, created a new branch to follow the github flow
and closed the previous pull request in the wrong branch

https://github.com/AdfPizarro/awesome_books/pull/6

2021-08-11 20:17 UTC, rloterh requested changes
Hi Mina & Adrian, 

You did extremely great on this project!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 


## Required Changes ♻️
- [ ] _Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Kindly check this comments marked [OPTIONAL]:

- [OPTIONAL]
Kindly provide **full name** of `Mina` and _Authors_ section of your ReadMe so as to make your ReadMe appear more professional.


Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 20:17 UTC, rloterh commented on dom.js
> +
- [ ] ESlint check is failing on this line. For cleaner code kindly ensure not leave empty lines which are not serving any purpose. Also kindly endeavor to fix **all** detected ESlint errors.

**ESlint Errors:**
![image](https://user-images.githubusercontent.com/12745474/129096215-e3e609f0-229f-4b17-bd4c-1352fdec580a.png)

2021-08-11 20:17 UTC, rloterh commented on index.html
>    <body>
- [ ]  Your app interface does not match with the given [wireframe template](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m3_style_core_elements.md). We actually want your design to as much as possible follow the provided wireframe template.. Kindly ensure to improve upon this aspect so as to achieve a cleaner interface.

**Your design interface:**
![image](https://user-images.githubusercontent.com/12745474/129095225-779c16a9-baad-4ce0-bb1c-8d407b1f2f0c.png)

**The original wireframe:**
![image](https://user-images.githubusercontent.com/12745474/129095437-6be5efaa-b1d5-41bb-a8c4-554d67ea4e0a.png)

2021-08-12 15:38 UTC, abruzy approved these changes
Hi Team 👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

_[OPTIONAL]_

- clear the input field after submission of the form, it would improve the user experience of your application

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-12 16:00 UTC, merged